name: Create Unity Package

on:
  push:
    branches: "master"
    tags: "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          mv LICENSE.* ./HRDisplay
          mkdir Assets
          mv HRDisplay ./Assets
          echo "Assets/HRDisplay.meta" > metaList
          find Assets/HRDisplay/ -name \*.meta >> metaList

      - run: mkdir output

      - name: Create unitypackage
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "output/HRDisplay.unitypackage"
          include-files: metaList

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          path: output
          name: package

      - name: Publish a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            output/HRDisplay.unitypackage
